### ISSUE TITLE
Переделать отображение заданий типа "выбор"

### ISSUE THREAD

**Issue by FraintSaad** [movsar/good-grades#40]
Отображение вопроса должно быть наверху, обычным текстом. На странице должны быть расположены объекты с ответами на вопрос, из которых нужно выбрать правильный вариант, без лишних элементов. Если выбран правильный ответ, выбранный вариант окрашивается в зеленый цвет(опционально. В общем говоря, надо выделить правильно выбранный вариант).

Набросок дизайна: 
![image](https://github.com/user-attachments/assets/6491d049-b5fe-44bd-a139-c0f3b4b735b3)

**Comment by FraintSaad** [comment]
Шаги реализации:

1. Переделать внешний вид в xaml, добавить нужные элементы(label, button-ы)
2. Реализовать логику под новый интерфейс
3. Реализовать сохранение ответов
4. Протестировать работу

**Comment by FraintSaad** [comment]
Если выбран неправильный ответ - выкинуть ошибку с сообщением о том, что ответ неправильный.

**Comment by movsar** [comment]
Я не обратил внимание на твой набросок, но если ты прочитаешь задание, он с заданием не сходится, соответственно то что ты реализоал тоже:

Задание:
> Наверху вопрос обычным текстом. Далее на странице расположены объекты с ответами. Нужно выбрать правильный вариант. То есть, никаких галочек и т.п. Нажимаешь объект. Если правильно, то, например, рамка окрашивается в зеленый цвет, если нет – то в красный.

Тут явно сказано что не должно быть никаких галочек (чекбоксов), квадратов и кругов. Надо чтобы окрашивались границы самих опций (текста) а не галочек.

**Comment by movsar** [comment]
Они просят сделать что-то подобное:
![image](https://github.com/user-attachments/assets/ed6dc01c-6e01-46cd-a2fe-d0c9018c7547)
