### ISSUE TITLE
Окошко после выполнения заданий

### ISSUE THREAD

**Issue by FraintSaad** [movsar/good-grades#41]
Если ученик выполняет все задания подряд, не возвращаясь на стартовую страницу, должно выходить окно с уведомлением «ХӀокху декъера дерриг тӀедахкарш кхочушдина ахь!»

**Comment by FraintSaad** [comment]
Шаги реализации:
1. Создать уведомление
2. Реализовать логику, по которой уведомление будет вызываться после прохождения
3. Протестировать

**Comment by movsar** [comment]
"Все задания" - что это подразумевает, все задания в разделе или все вопросы в одном задании?

**Comment by FraintSaad** [comment]
> "Все задания" - что это подразумевает, все задания в разделе или все вопросы в одном задании?

Все задания в разделе.
